/*
 * Board pin adaptation layer.
 *
 * SysConfig owns the physical pin assignments and generates
 * ti_msp_dl_config.h.  Application modules must use the BOARD_* aliases
 * below rather than SysConfig GPIO pin/port macros directly.  When wiring
 * changes, update this file after regenerating SysConfig; motor, chassis and
 * line-tracking logic should not need to change.
 */
#ifndef BOARD_PINS_H_
#define BOARD_PINS_H_

#include "ti_msp_dl_config.h"

/* Motor A: PWM PB10, AIN1 PB1, AIN2 PB11, EA PA7, EB PB14. */
#define BOARD_MOTOR_A_PWM_INSTANCE        PWM_MOTOR_AB_INST
#define BOARD_MOTOR_A_PWM_CHANNEL         DL_TIMER_CC_0_INDEX
#define BOARD_MOTOR_A_DIR1_PORT           GPIO_MOTOR_A_AIN_1_PORT
#define BOARD_MOTOR_A_DIR1_PIN            GPIO_MOTOR_A_AIN_1_PIN
#define BOARD_MOTOR_A_DIR2_PORT           GPIO_MOTOR_A_AIN_2_PORT
#define BOARD_MOTOR_A_DIR2_PIN            GPIO_MOTOR_A_AIN_2_PIN
#define BOARD_MOTOR_A_ENCODER_A_PORT      GPIO_MOTOR_A_EA_1_PORT
#define BOARD_MOTOR_A_ENCODER_A_PIN       GPIO_MOTOR_A_EA_1_PIN
#define BOARD_MOTOR_A_ENCODER_B_PORT      GPIO_MOTOR_A_EB_1_PORT
#define BOARD_MOTOR_A_ENCODER_B_PIN       GPIO_MOTOR_A_EB_1_PIN

/* Motor B: PWM PA24, BIN1 PA22, BIN2 PB24, EA PA15, EB PA17. */
#define BOARD_MOTOR_B_PWM_INSTANCE        PWM_MOTOR_AB_INST
#define BOARD_MOTOR_B_PWM_CHANNEL         DL_TIMER_CC_1_INDEX
#define BOARD_MOTOR_B_DIR1_PORT           GPIO_MOTOR_B_BIN_1_PORT
#define BOARD_MOTOR_B_DIR1_PIN            GPIO_MOTOR_B_BIN_1_PIN
#define BOARD_MOTOR_B_DIR2_PORT           GPIO_MOTOR_B_BIN_2_PORT
#define BOARD_MOTOR_B_DIR2_PIN            GPIO_MOTOR_B_BIN_2_PIN
#define BOARD_MOTOR_B_ENCODER_A_PORT      GPIO_MOTOR_B_EA_2_PORT
#define BOARD_MOTOR_B_ENCODER_A_PIN       GPIO_MOTOR_B_EA_2_PIN
#define BOARD_MOTOR_B_ENCODER_B_PORT      GPIO_MOTOR_B_EB_2_PORT
#define BOARD_MOTOR_B_ENCODER_B_PIN       GPIO_MOTOR_B_EB_2_PIN

/* Motor C: PWM PA0, CIN1 PB5, CIN2 PB4, EA PB12, EB PB13. */
#define BOARD_MOTOR_C_PWM_INSTANCE        PWM_MOTOR_CD_INST
#define BOARD_MOTOR_C_PWM_CHANNEL         DL_TIMER_CC_0_INDEX
#define BOARD_MOTOR_C_DIR1_PORT           GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_DIR1_PIN            GPIO_MOTOR_C_CIN_1_PIN
#define BOARD_MOTOR_C_DIR2_PORT           GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_DIR2_PIN            GPIO_MOTOR_C_CIN_2_PIN
#define BOARD_MOTOR_C_ENCODER_A_PORT      GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_ENCODER_A_PIN       GPIO_MOTOR_C_EA_3_PIN
#define BOARD_MOTOR_C_ENCODER_B_PORT      GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_ENCODER_B_PIN       GPIO_MOTOR_C_EB_3_PIN

/* Motor D: PWM PA1, DIN1 PA9, DIN2 PA8, EA PB15, EB PB16. */
#define BOARD_MOTOR_D_PWM_INSTANCE        PWM_MOTOR_CD_INST
#define BOARD_MOTOR_D_PWM_CHANNEL         DL_TIMER_CC_1_INDEX
#define BOARD_MOTOR_D_DIR1_PORT           GPIO_MOTOR_D_DIN_1_PORT
#define BOARD_MOTOR_D_DIR1_PIN            GPIO_MOTOR_D_DIN_1_PIN
#define BOARD_MOTOR_D_DIR2_PORT           GPIO_MOTOR_D_DIN_2_PORT
#define BOARD_MOTOR_D_DIR2_PIN            GPIO_MOTOR_D_DIN_2_PIN
#define BOARD_MOTOR_D_ENCODER_A_PORT      GPIO_MOTOR_D_EA_4_PORT
#define BOARD_MOTOR_D_ENCODER_A_PIN       GPIO_MOTOR_D_EA_4_PIN
#define BOARD_MOTOR_D_ENCODER_B_PORT      GPIO_MOTOR_D_EB_4_PORT
#define BOARD_MOTOR_D_ENCODER_B_PIN       GPIO_MOTOR_D_EB_4_PIN

/* Encoder IRQ routing: A/C/D EB are on GPIOB; B EB is on GPIOA. */
#define BOARD_ENCODER_GPIOB_IRQN          GPIO_MULTIPLE_GPIOB_INT_IRQN
#define BOARD_ENCODER_GPIOA_IRQN          GPIO_MOTOR_B_INT_IRQN
#define BOARD_ENCODER_GPIOB_PORT          GPIOB
#define BOARD_ENCODER_GPIOA_PORT          GPIOA
#define BOARD_ENCODER_GPIOB_MASK          (BOARD_MOTOR_A_ENCODER_B_PIN | \
                                           BOARD_MOTOR_C_ENCODER_B_PIN | \
                                           BOARD_MOTOR_D_ENCODER_B_PIN)
#define BOARD_ENCODER_GPIOA_MASK          BOARD_MOTOR_B_ENCODER_B_PIN

/* 8-channel grayscale module: AD0 PB27, AD1 PB26, AD2 PB23, OUT PA12. */
#define BOARD_GRAYSCALE_AD0_PORT          GPIO_GRAYSCALE_AD0_PORT
#define BOARD_GRAYSCALE_AD0_PIN           GPIO_GRAYSCALE_AD0_PIN
#define BOARD_GRAYSCALE_AD1_PORT          GPIO_GRAYSCALE_AD1_PORT
#define BOARD_GRAYSCALE_AD1_PIN           GPIO_GRAYSCALE_AD1_PIN
#define BOARD_GRAYSCALE_AD2_PORT          GPIO_GRAYSCALE_AD2_PORT
#define BOARD_GRAYSCALE_AD2_PIN           GPIO_GRAYSCALE_AD2_PIN
#define BOARD_GRAYSCALE_OUT_PORT          GPIO_GRAYSCALE_OUT_PORT
#define BOARD_GRAYSCALE_OUT_PIN           GPIO_GRAYSCALE_OUT_PIN
#define BOARD_GRAYSCALE_OUT_IOMUX         GPIO_GRAYSCALE_OUT_IOMUX

#endif /* BOARD_PINS_H_ */
