/*
 * 板级引脚适配层
 *
 * 物理引脚由 SysConfig 管理并生成 ti_msp_dl_config.h。业务模块统一使用
 * 本文件中的 BOARD_* 别名，不直接依赖 SysConfig 不稳定的分组宏名称。
 * 更换接线后，先重新生成 SysConfig，再只更新本文件；电机、底盘和巡线
 * 算法无需随引脚变化而修改。
 */
#ifndef BOARD_PINS_H_
#define BOARD_PINS_H_

#include "ti_msp_dl_config.h"

/* 电机 A（右后）：PWM PB10，AIN1 PB1，AIN2 PB11，EA PA7，EB PA25。 */
#define BOARD_MOTOR_A_PWM_INSTANCE        PWM_MOTOR_AB_INST
#define BOARD_MOTOR_A_PWM_CHANNEL         DL_TIMER_CC_0_INDEX
#define BOARD_MOTOR_A_DIR1_PORT           GPIO_MOTOR_A_AIN_1_PORT
#define BOARD_MOTOR_A_DIR1_PIN            GPIO_MOTOR_A_AIN_1_PIN
#define BOARD_MOTOR_A_DIR2_PORT           GPIO_MOTOR_A_AIN_2_PORT
#define BOARD_MOTOR_A_DIR2_PIN            GPIO_MOTOR_A_AIN_2_PIN
#define BOARD_MOTOR_A_ENCODER_A_PORT      GPIO_MOTOR_A_EA_1_PORT
#define BOARD_MOTOR_A_ENCODER_A_PIN       GPIO_MOTOR_A_EA_1_PIN
#define BOARD_MOTOR_A_ENCODER_B_PORT      GPIO_MOTOR_A_EB_1_PORT
#define BOARD_MOTOR_A_ENCODER_B_PIN       GPIO_MOTOR_A_EB_1_PIN

/* 电机 B（右前）：PWM PA24，BIN1 PA22，BIN2 PB24，EA PA15，EB PA17。 */
#define BOARD_MOTOR_B_PWM_INSTANCE        PWM_MOTOR_AB_INST
#define BOARD_MOTOR_B_PWM_CHANNEL         DL_TIMER_CC_1_INDEX
#define BOARD_MOTOR_B_DIR1_PORT           GPIO_MOTOR_B_BIN_1_PORT
#define BOARD_MOTOR_B_DIR1_PIN            GPIO_MOTOR_B_BIN_1_PIN
#define BOARD_MOTOR_B_DIR2_PORT           GPIO_MOTOR_B_BIN_2_PORT
#define BOARD_MOTOR_B_DIR2_PIN            GPIO_MOTOR_B_BIN_2_PIN
#define BOARD_MOTOR_B_ENCODER_A_PORT      GPIO_MOTOR_B_EA_2_PORT
#define BOARD_MOTOR_B_ENCODER_A_PIN       GPIO_MOTOR_B_EA_2_PIN
#define BOARD_MOTOR_B_ENCODER_B_PORT      GPIO_MOTOR_B_EB_2_PORT
#define BOARD_MOTOR_B_ENCODER_B_PIN       GPIO_MOTOR_B_EB_2_PIN

/* 电机 C（左前）：PWM PA0，CIN1 PB5，CIN2 PB4，EA PB12，EB PB13。 */
#define BOARD_MOTOR_C_PWM_INSTANCE        PWM_MOTOR_CD_INST
#define BOARD_MOTOR_C_PWM_CHANNEL         DL_TIMER_CC_0_INDEX
#define BOARD_MOTOR_C_DIR1_PORT           GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_DIR1_PIN            GPIO_MOTOR_C_CIN_1_PIN
#define BOARD_MOTOR_C_DIR2_PORT           GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_DIR2_PIN            GPIO_MOTOR_C_CIN_2_PIN
#define BOARD_MOTOR_C_ENCODER_A_PORT      GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_ENCODER_A_PIN       GPIO_MOTOR_C_EA_3_PIN
#define BOARD_MOTOR_C_ENCODER_B_PORT      GPIO_MOTOR_C_PORT
#define BOARD_MOTOR_C_ENCODER_B_PIN       GPIO_MOTOR_C_EB_3_PIN

/* 电机 D（左后）：PWM PA1，DIN1 PA8，DIN2 PA9，EA PB15，EB PB16。 */
#define BOARD_MOTOR_D_PWM_INSTANCE        PWM_MOTOR_CD_INST
#define BOARD_MOTOR_D_PWM_CHANNEL         DL_TIMER_CC_1_INDEX
#define BOARD_MOTOR_D_DIR1_PORT           GPIO_MOTOR_D_DIN_1_PORT
#define BOARD_MOTOR_D_DIR1_PIN            GPIO_MOTOR_D_DIN_1_PIN
#define BOARD_MOTOR_D_DIR2_PORT           GPIO_MOTOR_D_DIN_2_PORT
#define BOARD_MOTOR_D_DIR2_PIN            GPIO_MOTOR_D_DIN_2_PIN
#define BOARD_MOTOR_D_ENCODER_A_PORT      GPIO_MOTOR_D_EA_4_PORT
#define BOARD_MOTOR_D_ENCODER_A_PIN       GPIO_MOTOR_D_EA_4_PIN
#define BOARD_MOTOR_D_ENCODER_B_PORT      GPIO_MOTOR_D_EB_4_PORT
#define BOARD_MOTOR_D_ENCODER_B_PIN       GPIO_MOTOR_D_EB_4_PIN

/*
 * GPIOA/GPIOB 共用 GROUP1 中断入口。直接使用芯片级 IRQ 名称，避免
 * SysConfig 根据分组变化生成 GPIO_MOTOR_* 或 GPIO_MULTIPLE_* 等不稳定名称。
 */
#define BOARD_ENCODER_GPIOA_IRQN          GPIOA_INT_IRQn
#define BOARD_ENCODER_GPIOB_IRQN          GPIOB_INT_IRQn

/* 八路灰度模块：AD0 PB27，AD1 PB26，AD2 PB23，OUT PA12。 */
#define BOARD_GRAYSCALE_AD0_PORT          GPIO_GRAYSCALE_AD0_PORT
#define BOARD_GRAYSCALE_AD0_PIN           GPIO_GRAYSCALE_AD0_PIN
#define BOARD_GRAYSCALE_AD1_PORT          GPIO_GRAYSCALE_AD1_PORT
#define BOARD_GRAYSCALE_AD1_PIN           GPIO_GRAYSCALE_AD1_PIN
#define BOARD_GRAYSCALE_AD2_PORT          GPIO_GRAYSCALE_AD2_PORT
#define BOARD_GRAYSCALE_AD2_PIN           GPIO_GRAYSCALE_AD2_PIN
#define BOARD_GRAYSCALE_OUT_PORT          GPIO_GRAYSCALE_OUT_PORT
#define BOARD_GRAYSCALE_OUT_PIN           GPIO_GRAYSCALE_OUT_PIN
#define BOARD_GRAYSCALE_OUT_IOMUX         GPIO_GRAYSCALE_OUT_IOMUX

/* 任务按键均为上拉输入、低电平按下：PA29 启动，PA13 切换任务。 */
#define BOARD_TASK_START_PORT             GPIO_BTN_PORT
#define BOARD_TASK_START_PIN              GPIO_BTN_PIN_START_PIN
#define BOARD_TASK_START_IOMUX            GPIO_BTN_PIN_START_IOMUX
#define BOARD_TASK_CHANGE_PORT            GPIO_BTN_PORT
#define BOARD_TASK_CHANGE_PIN              GPIO_BTN_PIN_CHANGE_PIN
#define BOARD_TASK_CHANGE_IOMUX            GPIO_BTN_PIN_CHANGE_IOMUX

#endif /* BOARD_PINS_H_ */
